sudo: false
language: cpp

matrix:
  include:
   # Linux GCC Builds
    - os: linux
      compiler: gcc
      addons: &gcc8
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8', 'gcc-8','cmake']
      env: GCCVER='8' CXX_COMPILER='g++-8' C_COMPILER='gcc-8'

before_script:
  - cd ${TRAVIS_BUILD_DIR} 
  - export CXX=${CXX_COMPILER}
  - export CC=${C_COMPILER}
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export AR=gcc-ar-${GCCVER} ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export RANLIB=gcc-ranlib-${GCCVER} ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export NM=gcc-nm-${GCCVER} ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export TARGETBRANCH=gh-pages ; fi

# build
script :
  - ./tag.sh
  - cmake .
  - make
  - tar cvzf enPAC.tgz enPAC_on_the_fly 
  - cp  enPAC.tgz website/
  - ls -lah website/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: website/
  target_branch: $TARGETBRANCH
  on:
    branch: master
